### ISSUE TITLE
How to access and refer the original MeV?

### ISSUE THREAD

**Issue by SamGG** [dfci-cccb/mev#1048]
Hi,
Although I appreciate the Web version that you are developing, I would like to refer to the original MeV Java standalone version. It sounds like the www.tm4.org URL is now pointing exclusively to the WebMev.
This summer, we corrected bugs and improving the original MeV for small datasets in the framework of flow cytometry and Luminex data analysis. Our work is available at https://sourcesup.renater.fr/frs/?group_id=2569
Best,
Samuel

**Comment by yaoyu-e-wang** [comment]
Hello Sam,

Thank you for your support of the project.  The standalone MeV is still available on sourceforge at https://sourceforge.net/projects/mev-tm4/

Best,
Yaoyu
