### ISSUE TITLE
Cannot perform ZOOM or pathway enrighment

### ISSUE THREAD

**Issue by pcosper2** [dfci-cccb/mev#1049]
Hello,
I am following the tutorial on YouTube to practice this software using your example gene list provided. I am able to create selections from the PCA but I am not able to perform anything beyond this (Zoom or pathway analysis). I get the following error: Error while processing voom analysis undefined
Problem while running analysis: voom_myanalysis
Parameters: {"analysisName":"voom_myanalysis","name":"voom_myanalysis","experiment":{"name":"midtx","properties":{"selectionColor":"#cee3d","selectionDescription":""},"keys":[],"type":"column"},"control":{"name":"pretx","properties":{"selectionColor":"#8691a4","selectionDescription":""},"keys":[],"type":"column"},"datasetName":"200genes.txt","analysisType":"voom"}
Error: Error in contrasts.fit(fit, contrast.matrix[, "ExpvsContr"]) : trying to take contrast of non-estimable coefficient
This occurs on both a Windows PC and a Mac using the web-based application. Any suggestions are appreciated! 
Thank you!

**Comment by lev-kuznetsov** [comment]
You have created empty selections (sample sets) for both the control and the experiment. An easy way to create sets with samples in them would be for example from the PCA analysis page - drag an area on the scatter plot and then click "Create selections" above

**Comment by pcosper2** [comment]
Thank you for your response. However, I did create selections from the PCA page and they appeared in the drop down menus and on the left. Any other thoughts?

Thank you,

Pippa


Pippa Cosper, M.D., Ph.D.
PGY-4, Radiation Oncology
Washington University School of Medicine
Work cell 314-393-1629
[1473972932992_applicationsicon_rna.png]
________________________________

**Comment by lev-kuznetsov** [comment]
Would you mind sharing your dataset unless it's confidential of course
