### ISSUE TITLE
link to 'TM4 MeV Stand-Alone Client link' leads to 'HTTP Status 404 - '

### ISSUE THREAD

**Issue by plijnzaad** [dfci-cccb/mev#1053]
The link to 'TM4 MeV Stand-Alone Client link' on the http://mev.tm4.org homepage is broken. It links to http://www.tm4.org/mev.html which does not exist. (I was kinda hoping that I could more or less run it as a drop-in replacement of the old TIGR 4.9.* version ...)

**Comment by lev-kuznetsov** [comment]
Thanks, we'll fix the link in a few minutes, in the meantime the stand-alone version is available at https://sourceforge.net/projects/mev-tm4/
