### ISSUE TITLE
Can't import from GEO

### ISSUE THREAD

**Issue by SamGG** [dfci-cccb/mev#1054]
Hi,
I am interested in the GDS3966 GEO dataset, but I don't get feedback when I enter this ID in the GEO input query. Let me know what I did wrong.
Best.

**Comment by apartensky** [comment]
Hi Sam, I was just able to import your dataset. 
This seems to have been an issue on the NCBI side - a missing Access-Control-Allow-Origin header.
Please try again and report any issues.

**Comment by apartensky** [comment]
Hello Sam, what browser are you using?
I just reproduced your issue using Firefox It was due to ncbi moving their e-utils service to a secure url (https). Firefox could not handle the redirect. I deployed a fix. Please try your import and feel free to reopen the issue if still having problems.

**Comment by SamGG** [comment]
Hi. My browser is FF indeed, and I don't think about changing.
Thanks for your attention and caring about the problem.
I will do a trial.
Best.
