### ISSUE TITLE
GSEA is not working returns no sets and cannot set ID column for gene symbols

### ISSUE THREAD

**Issue by lungboyz** [dfci-cccb/mev#1056]

**Comment by lev-kuznetsov** [comment]
Gene identifier is assumed to be the first column of the dataset. GSEA could return an empty result set, this could be normal. I can't elaborate further without specifics of your case.

**Comment by lungboyz** [comment]
Happy new year!Can I send you the data table? Or share the work space some how?BestBrianBrian Cox, PhDAssistant ProfessorDepartment of PhysiologyFaculty of MedicineMedical Sciences Building, 3360University of Toronto1 King's College CircleToronto, ON Canada M5S 1A8Phone: 416-978-3241On Dec 30, 2016 1:27 PM, Lev Kuznetsov <notifications@github.com> wrote:Gene identifier is assumed to be the first column of the dataset. GSEA could return an empty result set, this could be normal. I can't elaborate further without specifics of your case.

**Comment by lev-kuznetsov** [comment]
You can share it via dropbox public folder or something like that, just post the link in this ticket

**Comment by lungboyz** [comment]
Hi Lev,
I noticed the MeV web site has been down for a couple of days. Will it be fixed soon?
Thanks
Brian

Brian Cox, PhD
Assistant Professor
Department of Physiology
Faculty of Medicine
Medical Sciences Building, 3360
University of Toronto
1 King's College Circle
Toronto, ON Canada M5S 1A8

Phone: 416-978-3241

**Comment by lev-kuznetsov** [comment]
Fixed DNS entry
