### ISSUE TITLE
CAST algorithm issues

### ISSUE THREAD

**Issue by dcovert2** [dfci-cccb/mev#1062]
Hello,

I have been studying how the Cluster Affinity Search Technique (CAST) algorithm is supposed to work from Ben-Dor's paper and was attempting to replicate it. While using the standalone MeV 4.8.1 on one of our servers to perform two 5 gene sample CAST runs to compare with, I noticed that although the first two genes to be added had a high enough pearson correlation coefficient, the third gene that was added to the same cluster had a sum that was less than the threshold multiplied by the cardinality of the cluster. So this didn't make much sense to me.

Below are two of the examples showing the first cluster of 3 genes and pearson correlaton matrix from R:

![sample1_threshold_0 8](https://cloud.githubusercontent.com/assets/25286807/22186783/5430116e-e0c9-11e6-89ce-79a8e20afa88.png)

![sample2_threshold_0 6](https://cloud.githubusercontent.com/assets/25286807/22186786/5a86ea6a-e0c9-11e6-8e02-570559a516f0.png)

Normalization was done using scaling in R so that the inputs could be seen before generating an output from MeV's CAST algorithm.

In the first example, threshold is 0.8. The problem occurs after 11402 and 12422 get added to the cluster and then 1004 is added with what should be a sum of 0.68+0.51 = 1.19 comparing against a requirement of 2*0.8=1.6

Second example has a threshold of 0.6. And the third gene to be added to this cluster should be 1123 with a sum of 0.64+0.11 = 0.75 compared to 2*0.6=1.2 as the requirement.

So one can see why I might be confused by these end results. At this point, either I have an improper understanding on how affinities are being updated or there is something different about how the MeV program is updating the affinities.

If someone could help me on this, I would greatly appreciate it. I also attempted to look up the source code on Github but could find nothing pertaining to the CAST algorithm yet.

Many thanks,
-Derek

**Comment by lev-kuznetsov** [comment]
The old client is no longer supported, honestly we have nobody left qualified to answer in depth questions on the old client anymore
