### ISSUE TITLE
MeV for Mac

### ISSUE THREAD

**Issue by werns2** [dfci-cccb/mev#1064]
Hi,
I am using MeV 4_6 for Mac and wonder whether there is an importer to apply gene annotation for Affymetrix HTA 2.0 arrays.
Thanks,
Werns

**Comment by lev-kuznetsov** [comment]
4.8.1 is the final version of the java client available for download for Mac available at https://sourceforge.net/projects/mev-tm4/ We have no expertise to support the java client at this point
