### ISSUE TITLE
TopGO Error

### ISSUE THREAD

**Issue by FrancesWong** [dfci-cccb/mev#1065]
Hi, 

I've been working with the software for a while now but I've suddenly been having issues running a TopGO analysis. I've changed none of the default settings and an using a geneset specified by a cluster through GeneSD. After pressing analyze, the status updates at the bottom state "Started topgo analysis topgo_FGF" and immediately after "Error while processing topgo analysis undefined"

This error has affected other users in my group.

Last time you asked me for the logs from Chrome Inspector > Errors so in case it's helpful in solving this problem ... 

Failed to load resource: the server responded with a status of 404 (Not Found)
8(unknown) AnnotationNotFoundOnServer: Could not find column annotations for dataset dataset_FINAL.txt--normalized-deseq at /annotations/dataset_FINAL.txt--normalized-deseq/annotation/column/new/dataset/command/core/export-project/dataset_FINAL.txt--normalized-deseq.google-refine.tar.gz
    at new AnnotationNotFoundOnServerError (http://mev.tm4.org/container/ui/dist/bundles/min/views.dataset.mo-fa6350d5.js:91:243)
    at http://mev.tm4.org/container/ui/dist/bundles/min/views.dataset.mo-fa6350d5.js:91:862
    at processQueue (<anonymous>:56:26291)
    at <anonymous>:56:26558
    at Scope.$eval (<anonymous>:57:7520)
    at Scope.$digest (<anonymous>:57:5320)
    at Scope.$apply (<anonymous>:57:7946)
    at done (<anonymous>:55:26686)
    at completeRequest (<anonymous>:55:30361)
    at XMLHttpRequest.xhr.onload (<anonymous>:55:31293)
(anonymous)
/container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:196 PollAnalysis error topgo_FGF Object
poll @ /container/ui/dist/bundles/min/app/views/dataset/views.dataset.module.js:196
http://mev.tm4.org/dataset?format=json Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
https://cdn.syndication.twimg.com/timeline/profile?callback=__twttr.callbac…reen_name=webmev&suppress_response_codes=true&t=1651867&with_replies=false Failed to load resource: net::ERR_INTERNET_DISCONNECTED
https://cdn.syndication.twimg.com/timeline/profile?callback=__twttr.callbac…reen_name=webmev&suppress_response_codes=true&t=1651867&with_replies=false Failed to load resource: net::ERR_NETWORK_CHANGED

**Comment by apartensky** [comment]
Hi Frances,
thank you for the error trace. In this case I don't see anything there that indicates TopGO failure.
After the analysis reports an "Error" you can click on it in the tree-view and you will see a more detailed error message on the right pane. Can you post that?
Thank you

**Comment by FrancesWong** [comment]
Hi, 

Problem while running analysis: topgo_FGF
Parameters: {"analysisName":"topgo_FGF","name":"topgo_FGF","genelist":["FGF10","FGF11","FGF12","FGF13","FGF14","FGF16","FGF17","FGF18","FGF19","FGF1","FGF20","FGF21","FGF22","FGF23","FGF2","FGF3","FGF4","FGF5","FGF6","FGF7","FGF8","FGF9","FGFBP1","FGFBP2","FGFBP3","FGFR1OP2","FGFR1OP","FGFR1","FGFR2","FGFR3","FGFR4","FGFRL1"],"species":"human","goType":"BP","testType":"fisher","pAdjust":"fdr","nodeSize":10,"datasetName":"dataset_FINAL.txt--normalized-deseq","analysisType":"topgo"}
Error: Error in file.path(mwd, "../topgo/domain/src/main/resources/HSAPIENS_ALL_GENES.txt") : object 'mwd' not found

Thanks!

**Comment by lev-kuznetsov** [comment]
Added missing topGo context data to the docker image
