### ISSUE TITLE
Cannot Sign In with gmail

### ISSUE THREAD

**Issue by competitiveinhibitor** [dfci-cccb/mev#1069]
3/16/2017 : The sign-in with gmail feature from the MeV website does not appear to be functional

**Comment by lev-kuznetsov** [comment]
What's happening when you try to sign in?

**Comment by competitiveinhibitor** [comment]
Hello Lev:

Here is a screen shot of the error that I get (in both Firefox and Chrome
browsers) Thanks for the support:

[image: Inline image 1]

**Comment by lev-kuznetsov** [comment]
Fixed expired oath credentials
