### ISSUE TITLE
DESeq Analysis Error

### ISSUE THREAD

**Issue by jfarid27** [dfci-cccb/mev#917]
Is it true that the DESeq analysis needs data that is in integer form @blawney ? It fails during the run using some non-integer data I have. Should we add a pre-analysis check somewhere that lets the user know the analysis won't work if this is the case @lev-kuznetsov ?

Error: 

Error in newCountDataSet(count_data, conditions) : 
  The countData is not integer.
Execution halted

[DEBUG] : edu.dfci.cccb.mev.deseq.domain.simple.StatelessScriptEngineFileBackedDESeqBuilder : DESeq script failed

**Comment by lev-kuznetsov** [comment]
I found our about this only after it was all implemented, I was waiting in Brian for a version that would expect data to be normalized, but I don't know when that's coming
