### ISSUE TITLE
LIMMA Quartile Bars are missing from the boxplot

### ISSUE THREAD

**Issue by yaoyu-e-wang** [dfci-cccb/mev#950]

**Comment by apartensky** [comment]
Also affects boxplot display in other statistical: Anova, tTest, DESeq. 
Reproduced in https://github.com/dfci-cccb/mev/tree/865e5a
![image](https://cloud.githubusercontent.com/assets/3672730/7054779/ce6cdb5e-de0c-11e4-9de3-fbf79f71a417.png)
